Add error handling and refactor task creation
TaskException: Exceptions for when configuring tasks.

UnknownCommandException: Exception when user input unknown command.

Tasks are now created through factory methods from their respective
tasks. Tasks are also now created based on input directly after given
command.

This is to allow TaskExceptions to be thrown exclusively by Tasks
instead of the main program.